title: Wow-L!fe
email: vikytech.mail@gmail.com
description: wow-life website
baseurl: ''
url: 'https://wow-life.in'
twitter_username:
github_username:
github:
  - metadata
author: Nirmal Kumar
facebook:
linkedin:

# Build settings
# markdown: kramdown
# theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed
logo: /assets/img/logo.png
# paginate: 2
show_downloads: false
destination: docs/
include:
  - CNAME
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
