---
#Dev configurations#
port: 4000
host: 0.0.0.0
safe: false

### content configuration ###
title: Wow-L!fe®
email: founder@wow-life.in
description: "Wow-L!fe - S!dh Healing \n Since 1996 \n As light eliminates darkness, thus 'S!dh eliminates disease' - Nirmal"
baseurl: ''
url: 'https://wow-life.in'
twitter_username:
github_username:
github:
  - metadata
author: Nirmal Kumar
keywords: "wow-life, yoga, rekhi, vastu, sidh healing, healing, inner peace, i am that, connecting to self, self help, self healing, peaceful mind, mind, body, soul"
favicon: "favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: G-W5P1NYEMW1
facebook: https://www.facebook.com/WowLifedr
instagram: https://www.instagram.com/wowlifedr
linkedin: https://www.linkedin.com/in/nirmal-kumar-b-ab34726

# Build settings
### site serving configuration ###
permalink: /:title
timezone: Asia/Kolkata
lsi: false
markdown: kramdown
# plugins:
  # - jekyll-paginate
sass:
  sass_dir: _sass
  style: compressed
logo: /assets/img/logo.svg
# paginate: 2
show_downloads: false
destination: docs/
include:
  - CNAME
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .gitignore
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - log
  - tmp
  - pages

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#5285EC'
  green:     '#58A55C'
  red:       '#D85040'
  yellow:    '#F2BD42'

kramdown:
  auto_ids:  false